apiVersion: v1
kind: Service
metadata:
  name: kubernetes-exporter
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: kubernetes-exporter
    name: kubernetes-exporter
spec:
  ports:
  - name: kubernetes-exporter
    protocol: TCP
    port: 9174
    targetPort: 9174
  selector:
    app: kubernetes-exporter
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubernetes-exporter
  labels:
    name: kubernetes-exporter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kubernetes-exporter
    spec:
      serviceAccountName: prometheus
      serviceAccount: prometheus
      containers:
      - name: kubernetes-exporter
        image: wisecity/kubernetes-exporter:latest 
        ports:
        - containerPort: 9174
          protocol: TCP
