apiVersion: v1
kind: Service
metadata:
  name: kubernetes-exporter 
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app:  kubernetes-exporter
    name: kubernetes-exporter
spec:
  ports:
  - name: kubernetes-exporter
    protocol: TCP
    port: 9174
    targetPort: 9174
  selector:
    app: kubernetes-exporter
  type: NodePort

