apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app:  kubernetes-exporter 
    name: kubernetes-exporter
spec:
  ports:
  - name: kubernetes-exporter
    protocol: TCP
    port: 9174
    targetPort: 9174
  selector:
    app: kubernetes-exporter
  type: NodePort






---
apiVersion: v1
kind: Service
metadata:
  annotations:
    # service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    # service.beta.kubernetes.io/external-traffic: OnlyLocal
    prometheus.io/scrape: 'true'
  labels:
    name: alertmanager
  name: alertmanager
  namespace: monitoring
spec:
  selector:
    app: alertmanager
  type: NodePort
  ports:
    - name: alertmanager
      protocol: TCP
      port: 9093
      targetPort: 9093
