apiVersion: v1
kind: Service                       
metadata:
  name: admin-tomcat                       
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 90
  selector:
    app: admin-tomcat

