apiVersion: v1
kind: ReplicationController
metadata:
  name: download-tomcat
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: download-tomcat
    spec:
      containers:
      - name: tomcat
        image: docker-dev.qregistry.local/qlove/download-tomcat:develop 
        imagePullPolicy: Always
        env:
        - name: isOnLine
          value: "false"
        - name: 'priestloglevel'
          value: "INFO"
        - name: XMN
          value: "64m"
        - name: XMS
          value: "128m"
        - name: XMX
          value: "584m"
        - name: XSS
          value: "256k"


        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "20m"
          limits:
            cpu: "500m"
      imagePullSecrets:
      - name: docker-dev.qregistry.local
