apiVersion: v1
kind: Service                       
metadata:
  name: download-tomcat                       
spec:
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: download-tomcat

