apiVersion: v1
kind: ReplicationController
metadata:
  name: gateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: docker-dev.qregistry.local/qlove/gateway:v20160830 
        imagePullPolicy: Always
#        command: [ "echo", "SUCCESS" ]
        env:
        - name: isOnLine
          value: "false"
        - name: 'LOG_LEVEL'
          value: "DEBUG"
        - name: INTERNAL_API
          value: "q-openresty:8888"

        ports:
        - containerPort: 8080
          hostPort: 8080
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        - containerPort: 9012
          hostPort: 9012
        - containerPort: 9013
          hostPort: 9013
        - containerPort: 1400
          hostPort: 1400

        resources:
          requests:
            cpu: "20m"
          limits:
            cpu: "500m"
        command:
          - "/opt/gateway/bin/start.sh"
      nodeSelector:
        kubernetes.io/hostname: "172.23.26.172"
