apiVersion: v1
kind: Service
metadata:
  name: gateway
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
  labels:
    app: gateway 
spec:
  type: NodePort
  selector:
    app: gateway 
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 80
  - name: https
    port: 443
    targetPort: 443
    nodePort: 4444
  - name: tcp-8080
    port: 8080
    targetPort: 8080
    nodePort: 8080
  - name: tcp-9012
    port: 9012
    targetPort: 9012
    nodePort: 9012
  - name: tcp-9013
    port: 9013
    targetPort: 9013
    nodePort: 9013
  - name: tcp-1400
    port: 1400
    targetPort: 1400
    nodePort: 1400
  selector:
    app: gateway
  sessionAffinity: ClientIP
  externalIPs:
    - 172.23.14.253
      
