apiVersion: v1
kind: ReplicationController
metadata:
  name: tomcat
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: docker-dev.qregistry.local/qlove/user-tomcat:develop
      imagePullSecrets:
      - name: docker-dev.qregistry.local
