apiVersion: v1
kind: Service
metadata:
  name: q-openresty
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
  labels:
    app: q-openresty
spec:
  type: NodePort
  selector:
    app: q-openresty
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 9080
  - name: https
    port: 443
    targetPort: 443
    nodePort: 9443
  - name: tcp
    port:  8888
    targetPort: 8888
    nodePort: 8887 

