apiVersion: v1
kind: ReplicationController
metadata:
  name: qlove-tomcat
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: qlove-tomcat
    spec:
      containers:
      - name: tomcat
        image: docker-dev.qregistry.local/qlove/qlove-tomcat:develop 
        imagePullPolicy: Always
        env:
        - name: isOnLine
          value: "false"
        - name: priestloglevel
          value: "INFO"
        - name: XMN
          value: "64m"
        - name: XMS
          value: "128m"
        - name: XMX
          value: "384m"
        - name: XSS
          value: "256k"
        - name: agoraAppID
          value: "215fdb1fc9e94dd69a6efcb8b03e9688"
        - name: agoraAppCertificate
          value: "53fa83d7b84344f1a27351d3e49834f8"
        - name: domain
          value: "http://sandboxapi.ziseyiliao.com"
        - name: duduAppid
          value: "bf27269d3f26b8c720c8900e78ba4b99"
        - name: AppSecret
          value: "107694bd786640b5fff1727c3aede80b0597573d7"



        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "20m"
          limits:
            cpu: "500m"
      imagePullSecrets:
      - name: docker-dev.qregistry.local
