apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: 58.132.182.70:5001/redis:alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: "200m"
          limits:
            cpu: "500m"
