apiVersion: v1
kind: Service                       
metadata:
  name: tomcat                       
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 8888 
  selector:
    app: tomcat

