apiVersion: v1
kind: Service                       
metadata:
  namespace: kube-system
  name: weave-scope-app                       
spec:
  type: NodePort
  ports:
    - port: 4040
      nodePort: 93
  selector:
    app: weave-scope-app-1668690219-jp512 

