apiVersion: v1
kind: Service
metadata:
  name: nginx-ts
  labels:
    app: nginx-ts
spec:
  type: NodePort
  selector:
    app: nginx-ts
  ports:
  - name: http
    port: 80
    targetPort: 80

---

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nginx-ts
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  template:
    metadata:
      labels:
        app: nginx-ts
    spec:
      containers:
      - name: me-nginx
        image: 175.25.178.156:5000/docker-product.qregistry.local/qlove/openresty
        ports:
        - containerPort: 80

        volumeMounts:
        - name: api 
          mountPath: /opt/openresty/nginx/conf/domains

      volumes:
      - name: api 
        configMap:
          name: nginx-domains
