apiVersion: v1
kind: ReplicationController
metadata:
  name: user-servcie
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: user-servcie
    spec:
      containers:
      - name: user-servcie
        image: docker-dev.qregistry.local/qlove/user-service:develop 
        imagePullPolicy: Always
        env:
        - name: "priest_log_level"
          value: "DEBUG"
        ports:
        - containerPort: 20880
        resources:
          requests:
            cpu: "20m"
          limits:
            cpu: "500m"
      imagePullSecrets:
      - name: docker-dev.qregistry.local
