apiVersion: v1
kind: ReplicationController
metadata:
  name: user-status-servcie
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: user-status-servcie
    spec:
      containers:
      - name: user-status-servcie
        image: docker-dev.qregistry.local/qlove/user-status-service:develop 
        imagePullPolicy: Always
       # env:
       # - name: "priest.log.level"
       #   value: "DEBUG"
        ports:
        - containerPort: 20880
        resources:
          requests:
            cpu: "20m"
          limits:
            cpu: "500m"
      imagePullSecrets:
      - name: docker-dev.qregistry.local
