apiVersion: v1
kind: ReplicationController
metadata:
  name: druid-im-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: druid-im-controller
    spec:
      containers:
      - name: druid-im-controller 
        image: docker-dev.qregistry.local/qlove/druid-im-controller:develop 
        imagePullPolicy: Always
       # env:
       # - name: "priest.log.level"
       #   value: "DEBUG"
        ports:
        - containerPort: 20880
        resources:
          requests:
            cpu: "20m"
          limits:
            cpu: "500m"
      imagePullSecrets:
      - name: docker-dev.qregistry.local
